name: build and zip web UI
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NAME: opendds-bench-scoreboard
    steps:
      - uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: install
        run: |
          cd ui
          npm ci
      - name: build
        run: |
          cd ui
          npm run build
      - name: zip
        run: |
          cd ui/public
          zip -r ${{env.NAME}} *
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.NAME}}
          path: ui/public/${{env.NAME}}.zip
