name: build and zip web UI
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - env:
          NAME: opendds-bench-scoreboard
      - uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: install
        run: |
          cd ui
          npm ci
      - name: build
        run: |
          cd ui
          npm run build
      - name: zipj
        run: zip --junk-paths $NAME ui/public/build/*
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: $NAME
          path: $NAME.zip
