name: Build and zip web UI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NAME: opendds-performance-dashboard
    steps:
      - name: Checkout opendds-performance-dashboard
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
      - name: Install UI
        run: |
          cd ui
          npm ci
      - name: Build UI
        run: |
          cd ui
          npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.NAME}}
          path: ui/dist
